name: Node.js CI

on:
  push

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Read node version from .nvmrc
      id: nvmrc
      run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '${{ steps.nvmrc.outputs.NODE_VERSION }}'
    - run: npm i -g yarn
    - run: yarn
    - run: yarn lint
    - run: yarn tsc
